# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import simple_pb2 as simple__pb2


class InferenceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Compute = channel.unary_unary(
        '/simple.Inference/Compute',
        request_serializer=simple__pb2.Input.SerializeToString,
        response_deserializer=simple__pb2.Output.FromString,
        )
    self.BatchedCompute = channel.stream_stream(
        '/simple.Inference/BatchedCompute',
        request_serializer=simple__pb2.Input.SerializeToString,
        response_deserializer=simple__pb2.Output.FromString,
        )


class InferenceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Compute(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BatchedCompute(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Compute': grpc.unary_unary_rpc_method_handler(
          servicer.Compute,
          request_deserializer=simple__pb2.Input.FromString,
          response_serializer=simple__pb2.Output.SerializeToString,
      ),
      'BatchedCompute': grpc.stream_stream_rpc_method_handler(
          servicer.BatchedCompute,
          request_deserializer=simple__pb2.Input.FromString,
          response_serializer=simple__pb2.Output.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'simple.Inference', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
