---
apiVersion: v1
kind: Endpoints
metadata:
  name: attis-devel
subsets:
- addresses:
  - ip: 10.0.0.10 # <== CHANGE ME!!!
  ports:
  - name: metrics
    port: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: attis-devel
  labels:
    app: attis-devel
spec:
  ports:
  - name: metrics
    port: 8002
    targetPort: 8002
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: attis-devel
  labels:
    scrape: nv-inference-metrics
spec:
  selector:
    matchLabels:
      app: attis-devel
  endpoints:
  - port: metrics
    interval: 2s
    honorLabels: true
