#!/usr/bin/env python3
import os

import click
import config_generator as cg

# Path(exists=False, file_okay=True, dir_okay=True, writable=False, readable=True, resolve_path=False)

FileType = click.Path(exists=True, file_okay=True, dir_okay=False, resolve_path=True)
PathType = click.Path(exists=True, file_okay=False, dir_okay=True, resolve_path=True)

@click.command()
@click.option("--engine", type=FileType, required=True)
@click.option("--concurrency", type=int, default=1)
@click.option("--name", type=FileType, default=None)
@click.option("--store", type=FileType, default=None)
def main(engine, concurrency, name, store):
    basename = os.path.basename(engine)
    model_name = name or basename.replace(".engine", "")
    print(cg.tensorrt_engine(model_name, engine, concurrency))
        # mkdir(model-store-yymmdd.hhmm/model_name)
        # mkdir(model-store-yymmdd.hhmm/model_name/0)
        # 
        # write config_file

if __name__ == "__main__":
    main()
