{
 "title": "YAIS",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Inference Rate (FPS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(yais_inference_load_ratio_count[5s])"
    },
    {
     "expr": "irate(yais_inference_load_ratio_count[5s])"
    }
   ]
  },
  {
   "title": "GPU Power (Watts)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "yais_gpus_power_usage" }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "yais_executor_queue_depth" }
   ]
  }
 ]
}